config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions

  get '/logout' => 'sessions#destroy'

  resources :recipes

  root to: 'recipes#index'
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :ingredients, :dependent => :destroy
	accepts_nested_attributes_for :ingredients, :reject_if => lambda { |a| a[:item].blank? }, :allow_destroy => true
	mount_uploader :img, ImgUploader
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
  	redirect_to recipes_path unless current_user
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	# Very Basic HTML Auth
	# http_basic_authenticate_with name: "admin", password: "foobar", except: :index

	def index
		@recipes = Recipe.all.order(created_at: :asc)
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def update
		@recipe = Recipe.find(params[:id])

		if @recipe.update_attributes(params.require(:recipe).permit(:title, :description, :steps, :img, ingredients_attributes: [:id, :_destroy, :item]))
			redirect_to recipes_path
		else
			render "edit"
		end		
	end

	def new
		@recipe = Recipe.new
		15.times { @recipe.ingredients.build }
	end

	def create
		@recipe = Recipe.new(params.require(:recipe).permit(:title, :description, :steps, :img, ingredients_attributes: [:id, :_destroy, :item]))

		if @recipe.save
			redirect_to recipes_path
		else
			render "new"
		end
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy
		redirect_to recipes_path
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to root_url
  	else
  		flash.now.alert = "Email or Password invalid"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to recipes_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_url,  notice: "You are logged in"
		else
			render "new"
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Campfire Kitchen</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js"></script>
</head>
<body>
<img src="<%= asset_path('grain.jpg') %>" class="grain">
<div class="header">
	<img src="<%= asset_path('Campfire_Logo_4a.svg') %>" alt="Campfire Cookery" class="logo">
	<div class="navlinks">
		<a id="home">Top</a>
		<span><a id="infobtn">Info</a></span>
		<% if current_user %>
		<br/>
		<a><%= link_to "New", new_recipe_path, class: 'new' %></a>
		<% end %>
		<br/>
		<% if current_user %>
			<p>Logged in as Admin<br/>
			<%= link_to "Log Out", '/logout' %>
			</p>	
		<% else %>
			<p><%= link_to "Admin", new_session_path %></p>			
		<% end %>
	</div>
</div>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>

	Title :
	<br/><%= f.text_field :title %>
	<br/>
	Description :
	<br/><%= f.text_area :description, :rows => 3 %>
	<br/>
	Steps :
	<br/><%= f.text_area :steps, :rows => 3 %>
	<br/>
	Photo : <%= f.file_field :img %>
	<br/>
	<br/>
	<div class="fields">
		<%= f.fields_for :ingredients do |builder| %>
			<%= builder.label :item, "Ingredient" %><br/>
			<%= builder.text_field :item %><br/>
		<% end %>
	<%= f.submit "Submit" %>
	</div>
<% end %>

app/views/recipes/edit.html.erb
<%= render partial: 'form' %>

<br/>

<%= link_to "Delete", :recipe, method: :delete, data: {confirm: "Are you sure? This action cannot be undone."} %>

app/views/recipes/index.html.erb
<!-- Main Body -->

<div class="recipes">

<!-- Intro -->

	<div class="intro" id="info">
		<h2>Welcome to<br/>Campfire Kitchen.</h2>
		<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p><img src="<%= asset_path('icon.svg') %>" class="bug">
	</div>

<!-- Recipes -->
<div id="top"></div>
<% @recipes.each do |r| %>

	<article>
		<h3>Recipe</h3>
		<h2><%= r.title %></h2><br/>
		<%= image_tag r.img.url %>
		<p><span><%= r.description.html_safe %></span></p>
		<img src="<%= asset_path('icon.svg') %>" class="bug">
		<h3>The Steps:</h3>
		<p><%= r.steps %></p>
		<!-- Ingredients -->
		<h3>The Ingredients:</h3>				
		<% for ingredients in r.ingredients %>
  		<ul>
  			<li><%=h ingredients.item %></li>
  		</ul>
		<% end %>
		<!-- Admin Links -->
		<% if current_user %><br/>
			<div class="adminlinks">
				<p>Admin Tools : </p>
				<%= link_to 'Edit', edit_recipe_path(r)%> | 
				<%= link_to "Delete", r, method: :delete, data: { confirm: "Are you sure?"} %>
			</div>
		<% end %>
	</article>

<% end %>

<!-- Footer -->

	<div class="footer">

			<p>©2016<br/>Daily Ops design studio & David Maupin</p>
			<p><span><a href="http://maupin.co/" target="blank">Contact</a></span></p>

	</div>

</div>

<!-- All Content, Logos, Images © David Maupin 2015 -->

app/views/recipes/new.html.erb
<%= render partial: 'form' %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<p>Form is invalid</p>
			<ul>
				<% user.errors.full_messages.each do |m| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label :password %><br/>
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %><br/>
		<%= f.password_field :password_confirmation %>
	</div>

	 <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>